OUTPUT_DATABASE = {
    "Geometry": [
        ("Range", "link_distance_km", "km"),
        ("TX Height", "tx_height_msl_m", "m"),
        ("RX Height", "rx_height_msl_m", "m"),
        ("TX Azimuth", "bearing_deg", "deg"),
        ("RX Azimuth", "rx_azimuth_deg", "deg"),
        ("TX Elevation", "beam_elevation_angle_deg", "deg"),
        ("RX Elevation", "rx_elevation_deg", "deg"),
        ("TX FOV", "tx_fov_mrad", "mrad"),
        ("RX FOV", "rx_fov_mrad", "mrad"),
        ("TX Half FOV", "tx_half_fov_mrad", "mrad"),
        ("RX Half FOV", "rx_half_fov_mrad", "mrad"),
        ("Receiver Solid Angle", "receiver_solid_angle_sr", "sr"),
        ("Min height", "minimum_height_above_sea_m", "m"),
        ("Beam Radius", "beam_radius_m", "m"),
        ("Beam Diameter", "beam_diameter_m", "m"),
        ("Capture Fraction", "capture_fraction", ""),
        ("Geometric Loss", "geometric_loss_dB", "dB"),
        ("LOS", "los", ""),
        ("LOS Margin", "los_margin_m", "m"),
        ("Optical Horizon", "optical_horizon_km", "km"),
        ("Curvature Drop", "earth_curvature_drop_m", "m"),
        ("Slant Range", "slant_range_m", "m"),
        ("Height Difference", "height_difference_m", "m"),
        ("Fresnel Radius", "fresnel_radius_m", "m"),
        ("Fresnel Clearance", "fresnel_clearance_pct", "%"),
        ("Propagation Type", "propagation_type", ""),
        ("Propagation Direction", "propagation_direction", ""),
        ("Effective Earth Radius", "effective_earth_radius_m", "m"),
    ],
    "Atmosphere": [
        ("Transmission", "atmospheric_transmission", ""),
        ("Refractivity", "refractivity_N", "N"),
        ("Differential Refraction", "differential_refraction_urad", "µrad"),
        ("Receiver Offset", "receiver_plane_offset_mm", "mm"),
        ("FSM Correction Required", "fsm_correction_required_urad", "µrad"),
        ("Duct Height", "duct_height_m", "m"),
        ("Duct Strength", "duct_strength", ""),
        ("Dew Point", "dew_point_C", "°C"),
        ("Air Density", "air_density_kg_m3", "kg/m³"),
        ("Water Vapor Density", "water_vapor_density_g_m3", "g/m³"),
        ("Surface Refractivity", "surface_refractivity_N", "N"),
        ("Refractivity Gradient", "refractivity_gradient_N_km", "N/km"),
        ("Modified Refractivity", "modified_refractivity_M", "M"),
    ],
    "Turbulence": [
        ("Cn2", "Cn2_m2_3", "m^(-2/3)"),
        ("Fried Parameter", "fried_parameter_m", "m"),
        ("Rytov Variance", "rytov_variance", ""),
        ("Scintillation Index", "scintillation_index", ""),
        ("Beam Wander", "beam_wander_urad", "µrad"),
        ("Beam Spread Factor", "beam_spread_factor", ""),
        ("Greenwood Frequency", "greenwood_frequency_Hz", "Hz"),
        ("Isoplanatic Angle", "isoplanatic_angle_urad", "µrad"),
        ("Coherence Time", "coherence_time_ms", "ms"),
        ("Scintillation Loss", "scintillation_loss_dB", "dB"),
        ("Surface Refractive Index", "surface_refractive_index", ""),
        ("dn/dz", "dn_dz", ""),
        ("Ray Curvature", "ray_curvature_1_m", "1/m"),
        ("Ray Bending Angle", "ray_bending_angle_urad", "µrad"),
        ("Elevation Bias", "effective_elevation_bias_urad", "µrad"),
        ("Beam Refraction Shift", "beam_refraction_shift_m", "m"),
    ],
    "Tracking": [
        ("Roll", "roll_rms_deg", "deg"),
        ("Pitch", "pitch_rms_deg", "deg"),
        ("Yaw", "yaw_rms_deg", "deg"),
        ("Ship LOS Jitter", "ship_los_jitter_urad", "µrad"),
        ("Tracking Error", "tracking_error_urad", "µrad"),
        ("Gimbal Error", "gimbal_tracking_error_urad", "µrad"),
        ("FSM Error", "fsm_residual_error_urad", "µrad"),
        ("Pointing Loss", "pointing_loss_dB", "dB"),
        ("Coupling Efficiency", "rx_coupling_efficiency", ""),
        ("Effective Capture Fraction", "effective_capture_fraction", ""),
        ("Total Jitter", "total_jitter_urad", "µrad"),
        ("Beam Offset", "beam_offset_m", "m"),
        ("Lock Probability", "lock_probability", ""),
        ("Tracking Probability", "tracking_probability", ""),
        ("Acquisition Probability", "acquisition_probability", ""),
        ("Gimbal Efficiency", "gimbal_tracking_efficiency", ""),
        ("FSM Efficiency", "fsm_tracking_efficiency", ""),
        ("FSM Stroke", "fsm_stroke_urad", "µrad"),
        ("Acquisition Error", "acquisition_error_urad", "µrad"),
    ],
    "Link": [
        ("Geometric Loss", "geometric_loss_dB", "dB"),
        ("Attenuation Coefficient", "visibility_gamma_dB_per_km", "dB/km"),
        ("Visibility Loss", "visibility_loss_dB", "dB"),
        ("Rain Loss", "rain_loss_dB", "dB"),
        ("Cloud Loss", "cloud_loss_dB", "dB"),
        ("Aerosol Loss", "aerosol_loss_dB", "dB"),
        ("Molecular Loss", "molecular_loss_dB", "dB"),
        ("Atmospheric Loss", "atmospheric_loss_dB", "dB"),
        ("Scintillation Loss", "scintillation_loss_dB", "dB"),
        ("Pointing Loss", "pointing_loss_dB", "dB"),
        ("TX Optical Loss", "tx_optical_loss_dB", "dB"),
        ("RX Optical Loss", "rx_optical_loss_dB", "dB"),
        ("Total Link Loss", "total_link_loss_dB", "dB"),
        ("Channel Efficiency", "channel_efficiency", ""),
        ("RX Coupling Efficiency", "rx_coupling_efficiency", ""),
        ("Availability", "availability_percent", "%"),
        ("Spot Diameter", "spot_diameter_m", "m"),
        ("Beam Diameter", "beam_diameter_m", "m"),
        ("Capture Fraction", "capture_fraction", ""),
        ("Link Margin", "link_margin_dB", "dB"),
    ],
    "Detector": [
        ("Channel Efficiency", "channel_efficiency", ""),
        ("Signal Count Rate", "signal_count_rate", "cps"),
        ("Background Count Rate", "background_count_rate", "cps"),
        ("Afterpulse Count Rate", "afterpulse_count_rate", "cps"),
        ("Deadtime Loss", "deadtime_loss_fraction", ""),
        ("Detection Probability", "detection_probability", ""),
        ("Total Counts", "total_counts", "counts"),
        ("Background Power", "background_power_W", "W"),
        ("Background Photon Rate", "background_photon_rate", "photons/s"),
        ("Moon Phase", "moon_phase_percent", "%"),
    ],
    
    "Design": [
        ("Recommended TX Aperture", "recommended_tx_aperture_mm", "mm"),
        ("Recommended RX Aperture", "recommended_rx_aperture_mm", "mm"),
        ("Recommended Divergence", "recommended_divergence_mrad", "mrad"),
        ("Predicted Availability", "predicted_availability_percent", "%"),
        ("Link Margin", "link_margin_dB", "dB"),
        ("Availability Day", "availability_day_percent", "%"),
        ("Availability Night", "availability_night_percent", "%"),
    ],
    "System": [
        ("Simulation Status", "simulation_status", ""),
        ("Debug Message", "debug_message", ""),
        ("LOS", "los", ""),
        ("Link Available", "link_available", ""),
        ("Link Blocked Reason", "link_blocked_reason", ""),
        ("System Health", "system_health", ""),
        ("Target QBER", "target_qber", "%"),
        ("Target Secure Key Rate", "target_secure_key_rate_bps", "bps"),
        ("Target Availability", "target_link_availability", "%"),
        ("Availability", "availability_percent", "%"),
        ("Simulation Time", "simulation_time_sec", "s"),
    ],
    "Solar": [
        ("Solar Elevation", "solar_elevation_deg", "deg"),
        ("Solar Azimuth", "solar_azimuth_deg", "deg"),
        ("Solar Azimuth Direction", "solar_azimuth_direction", ""),
        ("Solar Zenith", "solar_zenith_deg", "deg"),
        ("Solar Flux", "solar_flux_W_m2", "W/m²"),
        ("Solar Background", "solar_background_W", "W/sr/m²"),
        ("Solar Separation", "solar_separation_deg", "deg"),
        ("Solar TX Separation", "solar_tx_separation_deg", "deg"),
        ("Solar RX Separation", "solar_rx_separation_deg", "deg"),
        ("Sun Inside RX FOV", "sun_inside_rx_fov", ""),
        ("Sun Inside TX Beam", "sun_inside_tx_beam", ""),
        ("Solar Overlap", "solar_overlap_fraction", ""),
        ("Solar Angle Factor", "solar_angle_factor", ""),
        ("Filter Overlap", "filter_overlap_fraction", ""),
        ("Filtered Background", "filtered_background_fraction", ""),
        ("Moon Background", "moon_background_W", "W/sr/m²"),
        ("Moon Phase", "moon_phase_percent", "%"),
        ("Sky Background", "sky_background_W", "W/sr/m²"),
        ("Sky Radiance", "sky_radiance_W_sr_m2", "W/sr/m²"),
        ("Background Power", "background_power_W", "W"),
        ("Background Photon Rate", "background_photon_rate", "photons/s"),
    ],
    "Terrain": [
        ("Dominant Surface", "dominant_surface", ""),
        ("Land Percentage", "land_percentage", "%"),
        ("Sea Percentage", "sea_percentage", "%"),
        ("Coastal Path", "coastal_path", ""),
        ("Terrain Elevation", "terrain_elevation_m", "m"),
        ("Surface Elevation", "surface_elevation_m", "m"),
        ("Lowest LOS Height", "lowest_los_height_m", "m"),
        ("Lowest LOS Distance", "lowest_los_distance_m", "m"),
        ("Highest LOS Height", "highest_los_height_m", "m"),
        ("Highest LOS Distance", "highest_los_distance_m", "m"),
        ("Minimum Clearance", "minimum_clearance_m", "m"),
        ("Maximum Clearance", "maximum_clearance_m", "m"),
        ("Average Ground Height", "average_ground_height_m", "m"),
    ],
    "Slicing": [
        ("Slice Count", "slice_count", ""),
        ("Slice Accuracy", "slice_accuracy", ""),
        ("Slice Generation", "slice_generation_method", ""),
        ("Minimum Slice Length", "minimum_slice_length_m", "m"),
        ("Maximum Slice Length", "maximum_slice_length_m", "m"),
        ("Average Slice Length", "average_slice_length_m", "m"),
        ("Link Blocked", "link_blocked", ""),
    ],
}

from core.qkd_output_database import QKD_OUTPUT_DATABASE
_qkd_outputs = {}
for category, outputs in QKD_OUTPUT_DATABASE.items():
    for display_name, state_var, unit in outputs:
        if display_name not in _qkd_outputs:
            _qkd_outputs[display_name] = (display_name, state_var, unit)

OUTPUT_DATABASE["QKD Outputs"] = list(_qkd_outputs.values())

