QKD_OUTPUT_DATABASE = {
    "Common": [
        ("Channel Efficiency", "channel_efficiency", ""),
        ("Binary Entropy", "binary_entropy", ""),
        ("Error Correction Leakage", "error_correction_leakage", ""),
        ("Authentication Cost", "authentication_cost", ""),
        ("Secret Fraction", "secret_fraction", ""),
        ("Final Secure Key Rate", "final_secure_key_rate", "bps"),
    ],
    "Detector": [
        ("Signal Count Rate", "signal_count_rate", "cps"),
        ("Background Count Rate", "background_count_rate", "cps"),
        ("Dark Count Rate", "dark_count_rate", "cps"),
        ("Afterpulse Rate", "afterpulse_count_rate", "cps"),
        ("Deadtime Loss", "deadtime_loss_fraction", ""),
        ("Total Counts", "total_counts", "cps"),
        ("Detector Saturation", "detector_saturation", ""),
    ],
    "Key Rates": [
        ("Raw Key Rate", "raw_key_rate", "bps"),
        ("Sifted Key Rate", "sifted_key_rate", "bps"),
        ("Secure Key Rate", "secure_key_rate", "bps"),
    ],
    "Security": [
        ("QBER", "qber", "%"),
        ("Binary Entropy", "binary_entropy", ""),
        ("Error Correction Leakage", "error_correction_leakage", ""),
        ("Privacy Amplification Loss", "privacy_amplification_loss", ""),
        ("Authentication Cost", "authentication_cost", ""),
        ("Secret Fraction", "secret_fraction", ""),
    ],
    "BB84": [
        ("Raw Key Rate", "raw_key_rate", "bps"),
        ("Sifted Key Rate", "sifted_key_rate", "bps"),
        ("QBER", "qber", "%"),
        ("Binary Entropy", "binary_entropy", ""),
        ("Error Correction Leakage", "error_correction_leakage", ""),
        ("Privacy Amplification", "privacy_amplification_loss", ""),
        ("Authentication Cost", "authentication_cost", ""),
        ("Secret Fraction", "secret_fraction", ""),
        ("Secure Key Rate", "secure_key_rate", "bps"),
    ],
    "Decoy BB84": [
        ("Signal Gain", "signal_gain", ""),
        ("Weak Gain", "weak_gain", ""),
        ("Vacuum Gain", "vacuum_gain", ""),
        ("Signal QBER", "signal_qber", "%"),
        ("Weak QBER", "weak_qber", "%"),
        ("Single Photon Yield", "single_photon_yield", ""),
        ("Single Photon Gain", "single_photon_gain", ""),
        ("Single Photon Error", "single_photon_error_rate", "%"),
        ("Multi Photon Fraction", "multi_photon_fraction", ""),
        ("Secret Fraction", "secret_fraction", ""),
        ("Secure Key Rate", "secure_key_rate", "bps"),
    ],
    "B92": [
        ("Detection Probability", "detection_probability", ""),
        ("Conclusive Probability", "conclusive_probability", ""),
        ("Raw Key Rate", "raw_key_rate", "bps"),
        ("QBER", "qber", "%"),
        ("Secret Fraction", "secret_fraction", ""),
        ("Secure Key Rate", "secure_key_rate", "bps"),
    ],
    "E91": [
        ("Singles Alice", "singles_alice_hz", "Hz"),
        ("Singles Bob", "singles_bob_hz", "Hz"),
        ("Coincidence Rate", "coincidence_rate_hz", "Hz"),
        ("Visibility", "visibility", "%"),
        ("Bell Parameter", "bell_parameter", ""),
        ("QBER", "qber", "%"),
        ("Secret Fraction", "secret_fraction", ""),
        ("Secure Key Rate", "secure_key_rate", "bps"),
    ],
    "BBM92": [
        ("Coincidence Rate", "coincidence_rate_hz", "Hz"),
        ("Sifted Coincidence Rate", "sifted_coincidence_rate_hz", "Hz"),
        ("QBER", "qber", "%"),
        ("Secret Fraction", "secret_fraction", ""),
        ("Secure Key Rate", "secure_key_rate", "bps"),
    ],
}
