QKD_INPUT_DATABASE = {
    "PROTOCOL": {
        "BB84": [
            ("Basis Probability Z", 0.5, "", "basis_probability_z"),
            ("Basis Probability X", 0.5, "", "basis_probability_x"),
            ("Error Correction Efficiency", 1.16, "", "error_correction_factor"),
            ("Authentication Cost", 0.0, "bits", "authentication_cost_bits"),
            ("Finite Key Block Size", 1000000.0, "bits", "finite_key_block_size"),
            ("PPR", 200, "MHz", "pulse_rate_mhz"),
            ("Afterpulse Probability", 0.01, "", "afterpulse_probability"),
            ("Polarization Visibility", 0.99, "", "polarization_visibility"),
            ("Timing Jitter", 50.0, "ps", "timing_jitter_ps"),
            ("Total Detection Probability", 0.1, "", "total_detection_probability"),
        ],
        "Decoy BB84": [
            ("Mean Photon Number", 0.5, "", "mean_photon_number"),
            ("Weak Decoy Intensity", 0.1, "", "weak_decoy_intensity"),
            ("Vacuum Intensity", 0.0, "", "vacuum_decoy_intensity"),
            ("Signal Probability", 0.8, "", "signal_probability"),
            ("Weak Decoy Probability", 0.15, "", "weak_decoy_probability"),
            ("Vacuum Probability", 0.05, "", "vacuum_probability"),
            ("PPR", 200, "MHz", "pulse_rate_mhz"),
            ("Afterpulse Probability", 0.01, "", "afterpulse_probability"),
            ("Polarization Visibility", 0.99, "", "polarization_visibility"),
            ("Timing Jitter", 50.0, "ps", "timing_jitter_ps"),
            ("Total Detection Probability", 0.1, "", "total_detection_probability"),
        ],
        "B92": [
            ("State Overlap Angle", 45.0, "deg", "state_overlap_angle_deg"),
            ("Non-orthogonal Overlap", 0.707, "", "non_orthogonal_overlap"),
            ("Conclusive Probability", 0.25, "", "conclusive_probability"),
            ("Error Correction Efficiency", 1.16, "", "error_correction_factor"),
            ("Afterpulse Probability", 0.01, "", "afterpulse_probability"),
            ("Polarization Visibility", 0.99, "", "polarization_visibility"),
            ("Timing Jitter", 50.0, "ps", "timing_jitter_ps"),
            ("Total Detection Probability", 0.1, "", "total_detection_probability"),
        ],
        "E91": [
            ("PGR (MHz)", 10.0, "MHz", "pair_generation_rate_mhz"),
            ("Coincidence Window", 1.0, "ns", "coincidence_window_ns"),
            ("Coincidence Efficiency", 0.8, "", "coincidence_efficiency"),
            ("Alice Basis Probability", 0.5, "", "alice_basis_probability"),
            ("Bob Basis Probability", 0.5, "", "bob_basis_probability"),
            ("Bell Basis Angles", 22.5, "deg", "bell_basis_angles_deg"),
            ("Afterpulse Probability", 0.01, "", "afterpulse_probability"),
            ("Polarization Visibility", 0.99, "", "polarization_visibility"),
            ("Timing Jitter", 50.0, "ps", "timing_jitter_ps"),
            ("Total Detection Probability", 0.1, "", "total_detection_probability"),
        ],
        "BBM92": [
            ("Coincidence Window", 1.0, "ns", "coincidence_window_ns"),
            ("Coincidence Efficiency", 0.8, "", "coincidence_efficiency"),
            ("Source Brightness", 1e6, "cps", "entangled_source_brightness"),
            ("Pair Production Probability", 0.1, "", "pair_production_probability"),
            ("Afterpulse Probability", 0.01, "", "afterpulse_probability"),
            ("Polarization Visibility", 0.99, "", "polarization_visibility"),
            ("Timing Jitter", 50.0, "ps", "timing_jitter_ps"),
            ("Total Detection Probability", 0.1, "", "total_detection_probability"),
        ],
    },
}
