INPUT_LIMITS = {
    "link_distance_km": (0.001, 1e6),
    "tx_height_msl_m": (-1000, 100000),
    "rx_height_msl_m": (-1000, 100000),
    "minimum_height_above_sea_m": (0, 100000),
    "tx_latitude_deg": (-90, 90),
    "tx_longitude_deg": (-180, 180),
    "rx_latitude_deg": (-90, 90),
    "rx_longitude_deg": (-180, 180),
    "month": (1, 12),
    "day": (1, 31),
    "time_of_day_hr": (0, 24),
    "moon_phase_percent": (0, 100),
    "effective_earth_radius_factor": (1.0, 9.0),
    "wavelength_nm": (0.1, 100000),
    "source_bandwidth_nm": (0.001, 1000),
    "tx_beam_divergence_mrad": (0.001, 1000),
    "tx_aperture_mm": (0.001, 10000),
    "tx_beam_quality_M2": (1.0, 100),
    "pulse_rate_mhz": (1e-6, 1e6),
    "rx_aperture_mm": (0.001, 10000),
    "rx_fov_mrad": (0.001, 1000),
    "rx_filter_center_wavelength_nm": (0.1, 100000),
    "rx_filter_bandwidth_nm": (0.001, 1000),
    "tx_temperature_C": (-273.15, 1000),
    "tx_humidity_pct": (0, 100),
    "tx_rain_rate_mm_hr": (0, 500),
    "tx_visibility_km": (0.001, 1000),
    "tx_wind_speed_m_s": (0, 100),
    "tx_pressure_hPa": (0.001, 2000),
    "tx_cloud_cover_percent": (0, 100),
    "tx_cloud_base_height_m": (0, 20000),
    "tx_aerosol_alpha": (0, 10),
    "tx_optical_loss_dB": (0, 100),
    "rx_temperature_C": (-273.15, 1000),
    "rx_humidity_pct": (0, 100),
    "rx_rain_rate_mm_hr": (0, 500),
    "rx_visibility_km": (0.001, 1000),
    "rx_wind_speed_m_s": (0, 100),
    "rx_pressure_hPa": (0.001, 2000),
    "rx_cloud_cover_percent": (0, 100),
    "rx_cloud_base_height_m": (0, 20000),
    "rx_aerosol_alpha": (0, 10),
    "rx_optical_loss_dB": (0, 100),
    "roll_rms_deg": (-180, 180),
    "pitch_rms_deg": (-180, 180),
    "yaw_rms_deg": (-180, 180),
    "gimbal_bw_hz": (0.1, 1000),
    "fsm_bw_hz": (1, 10000),
    "control_loop_bw_hz": (1, 10000),
    "sampling_frequency_hz": (1, 100000),
    "encoder_resolution_urad": (0.01, 1000),
    "pointing_accuracy_urad": (0.01, 1000),
    "servo_response_ms": (0.1, 1000),
    "acquisition_uncertainty_urad": (0.1, 10000),
    "tracking_jitter_urad": (0.01, 1000),
    "stabilization_performance_pct": (0.1, 100),
    "sea_state": (0, 9),
    "wave_height_m": (0, 30),
    "wave_slope_rms_deg": (0, 90),
    "evap_duct_height_m": (0, 1000),
    "marine_BL_height_m": (10, 3000),
    "sea_surface_temperature_C": (-273.15, 1000),
    "wave_period_s": (0.1, 300),
    "wave_direction_deg": (0, 360),
    "ship_heading_deg": (0, 360),
    "detector_efficiency": (0, 1),
    "dark_count_rate": (0, 1e12),
    "detector_deadtime_ns": (0.1, 1e6),
    "basis_probability_z": (0, 1),
    "basis_probability_x": (0, 1),
    "error_correction_factor": (1.0, 2.0),
    "authentication_cost_bits": (0, 1e12),
    "finite_key_block_size": (1, 1e15),
    "afterpulse_probability": (0, 1),
    "polarization_visibility": (0, 1),
    "timing_jitter_ps": (0, 1e6),
    "total_detection_probability": (0, 1),
    "mean_photon_number": (0, 1e6),
    "weak_decoy_intensity": (0, 1e6),
    "vacuum_decoy_intensity": (0, 1e6),
    "signal_probability": (0, 1),
    "weak_decoy_probability": (0, 1),
    "vacuum_probability": (0, 1),
    "state_overlap_angle_deg": (0, 90),
    "non_orthogonal_overlap": (0, 1),
    "conclusive_probability": (0, 1),
    "pair_generation_rate_mhz": (1e-6, 1e6),
    "coincidence_window_ns": (0, 1e6),
    "coincidence_efficiency": (0, 1),
    "alice_basis_probability": (0, 1),
    "bob_basis_probability": (0, 1),
    "bell_basis_angles_deg": (0, 360),
    "entangled_source_brightness": (0, 1e12),
    "pair_production_probability": (0, 1),
}
from core.settings_manager import SettingsManager
_settings = SettingsManager().load()
_det_defaults = _settings.get("detector_defaults", {})

INPUT_DATABASE = {
    "MISSION": [
        ("Range", 10, "km", "link_distance_km"),
        ("TX height", 10, "m", "tx_height_msl_m"),
        ("RX height", 15, "m", "rx_height_msl_m"),
        ("Minimum Height Above Sea", 5, "m", "minimum_height_above_sea_m"),
        ("TX Latitude", 28.6139, "°", "tx_latitude_deg"),
        ("TX Longitude", 77.2090, "°", "tx_longitude_deg"),
        ("RX Latitude", 28.7041, "°", "rx_latitude_deg"),
        ("RX Longitude", 77.1025, "°", "rx_longitude_deg"),
        ("Month", 6, "", "month"),
        ("Day", 15, "", "day"),
        ("Time of Day", 12, "hr", "time_of_day_hr"),
        ("Moon Phase", 50, "%", "moon_phase_percent"),
        ("Effective Earth Radius Factor", 1.333, "", "effective_earth_radius_factor"),
    ],
    "TX_OPTICS": [
        # -----------------------
        # TRANSMITTER
        # -----------------------
        ("Wavelength", 1550, "nm", "wavelength_nm"),
        ("Source Bandwidth", 2.0, "nm", "source_bandwidth_nm"),
        ("Divergence", 0.1, "mrad", "tx_beam_divergence_mrad"),
        ("TX aperture", 150, "mm", "tx_aperture_mm"),
        ("Beam Quality M2", 1.0, "", "tx_beam_quality_M2"),
        ("TX Optical Loss", 1.0, "dB", "tx_optical_loss_dB"),
    ],
    "RX_OPTICS": [
        # -----------------------
        # RECEIVER
        # -----------------------
        ("RX aperture", 600, "mm", "rx_aperture_mm"),
        ("FOV", 1.0, "mrad", "rx_fov_mrad"),
        ("RX Filter Center WL", 1550, "nm", "rx_filter_center_wavelength_nm"),
        ("RX Filter Bandwidth", 0.5, "nm", "rx_filter_bandwidth_nm"),
        ("RX Optical Loss", 1.0, "dB", "rx_optical_loss_dB"),
    ],
    "TX_ENVIRONMENT": [
        ("Temperature", 25, "C", "tx_temperature_C"),
        ("Humidity", 80, "%", "tx_humidity_pct"),
        ("Rain Rate", 0, "mm/hr", "tx_rain_rate_mm_hr"),
        ("Visibility", 10, "km", "tx_visibility_km"),
        ("Wind", 5, "m/s", "tx_wind_speed_m_s"),
        ("Pressure", 1013, "hPa", "tx_pressure_hPa"),
        ("Cloud Cover", 0, "%", "tx_cloud_cover_percent"),
        ("Cloud Base Height", 2000, "m", "tx_cloud_base_height_m"),
        ("Aerosol Alpha", 1.3, "", "tx_aerosol_alpha"),
    ],
    "RX_ENVIRONMENT": [
        ("Temperature", 25, "C", "rx_temperature_C"),
        ("Humidity", 80, "%", "rx_humidity_pct"),
        ("Rain Rate", 0, "mm/hr", "rx_rain_rate_mm_hr"),
        ("Visibility", 10, "km", "rx_visibility_km"),
        ("Wind", 5, "m/s", "rx_wind_speed_m_s"),
        ("Pressure", 1013, "hPa", "rx_pressure_hPa"),
        ("Cloud Cover", 0, "%", "rx_cloud_cover_percent"),
        ("Cloud Base Height", 2000, "m", "rx_cloud_base_height_m"),
        ("Aerosol Alpha", 1.3, "", "rx_aerosol_alpha"),
    ],
    "TRACKING": [
        ("Roll", 0, "deg", "roll_rms_deg"),
        ("Pitch", 0, "deg", "pitch_rms_deg"),
        ("Yaw", 0, "deg", "yaw_rms_deg"),
        ("Gimbal BW", _settings.get("tracking_defaults", {}).get("gimbal_bandwidth_hz", 10.0), "Hz", "gimbal_bw_hz"),
        ("FSM BW", _settings.get("tracking_defaults", {}).get("fsm_bandwidth_hz", 200.0), "Hz", "fsm_bw_hz"),
        ("Control Loop BW", _settings.get("tracking_defaults", {}).get("control_loop_bandwidth_hz", 500.0), "Hz", "control_loop_bw_hz"),
        ("Sampling Frequency", _settings.get("tracking_defaults", {}).get("sampling_frequency_hz", 1000.0), "Hz", "sampling_frequency_hz"),
        ("Encoder Resolution", _settings.get("tracking_defaults", {}).get("encoder_resolution_urad", 1.0), "urad", "encoder_resolution_urad"),
        ("Pointing Accuracy", _settings.get("tracking_defaults", {}).get("pointing_accuracy_urad", 2.0), "urad", "pointing_accuracy_urad"),
        ("Servo Response", _settings.get("tracking_defaults", {}).get("servo_response_ms", 2.0), "ms", "servo_response_ms"),
        ("Acquisition Uncertainty", _settings.get("tracking_defaults", {}).get("acquisition_uncertainty_urad", 10.0), "urad", "acquisition_uncertainty_urad"),
        ("Tracking Jitter", _settings.get("tracking_defaults", {}).get("tracking_jitter_urad", 1.0), "urad", "tracking_jitter_urad"),
        ("Stabilization %", _settings.get("tracking_defaults", {}).get("stabilization_performance_pct", 98.0), "%", "stabilization_performance_pct"),
    ],
    "MARINE": [
        ("Sea State", 3, "", "sea_state"),
        ("Wave Height", 1, "m", "wave_height_m"),
        ("Wave Slope", 2, "deg", "wave_slope_rms_deg"),
        ("Evap Duct Height", 20, "m", "evap_duct_height_m"),
        ("Marine BL Height", 500, "m", "marine_BL_height_m"),
        ("Sea Surface Temp", 27, "C", "sea_surface_temperature_C"),
        ("Wave Period", 5, "s", "wave_period_s"),
        ("Wave Direction", 0, "deg", "wave_direction_deg"),
        ("Ship Heading", 0, "deg", "ship_heading_deg"),
    ],
}
DETECTOR_DATABASE = {
    "SNSPD": [
        ("Detector QE", _det_defaults.get("SNSPD", {}).get("qe", 0.90), "", "detector_efficiency"),
        ("Dark Count Rate", _det_defaults.get("SNSPD", {}).get("dcr_cps", 10), "cps", "dark_count_rate"),
        ("Detector Deadtime", _det_defaults.get("SNSPD", {}).get("dead_time_ns", 20), "ns", "detector_deadtime_ns"),
    ],
    "SPAD": [
        ("Detector QE", _det_defaults.get("SPAD", {}).get("qe", 0.20), "", "detector_efficiency"),
        ("Dark Count Rate", _det_defaults.get("SPAD", {}).get("dcr_cps", 1000), "cps", "dark_count_rate"),
        ("Detector Deadtime", _det_defaults.get("SPAD", {}).get("dead_time_ns", 200), "ns", "detector_deadtime_ns"),
    ],
    "APD": [
        ("Detector QE", _det_defaults.get("APD", {}).get("qe", 0.45), "", "detector_efficiency"),
        ("Dark Count Rate", _det_defaults.get("APD", {}).get("dcr_cps", 5000), "cps", "dark_count_rate"),
        ("Detector Deadtime", _det_defaults.get("APD", {}).get("dead_time_ns", 30), "ns", "detector_deadtime_ns"),
    ],
    "PMT": [
        ("Detector QE", _det_defaults.get("PMT", {}).get("qe", 0.30), "", "detector_efficiency"),
        ("Dark Count Rate", _det_defaults.get("PMT", {}).get("dcr_cps", 500), "cps", "dark_count_rate"),
        ("Detector Deadtime", _det_defaults.get("PMT", {}).get("dead_time_ns", 10), "ns", "detector_deadtime_ns"),
    ],
    "TES": [
        ("Detector QE", _det_defaults.get("TES", {}).get("qe", 0.98), "", "detector_efficiency"),
        ("Dark Count Rate", _det_defaults.get("TES", {}).get("dcr_cps", 0.1), "cps", "dark_count_rate"),
        ("Detector Deadtime", _det_defaults.get("TES", {}).get("dead_time_ns", 1000), "ns", "detector_deadtime_ns"),
    ],
}

from core.qkd_input_database import QKD_INPUT_DATABASE

_qkd_inputs = {}
for protocol, params in QKD_INPUT_DATABASE["PROTOCOL"].items():
    for name, value, unit, state_var in params:
        if name not in _qkd_inputs:
            _qkd_inputs[name] = (name, value, unit, state_var)

INPUT_DATABASE["QKD Inputs"] = list(_qkd_inputs.values())
